### ISSUE TITLE
object address with dbghelp

### ISSUE THREAD

**Issue by eyalgolan1337** [jeremy-rifkin/cpptrace#100]
The new `object_address` field in `stacktrace_frame` is excellent when resolving frames using libdwarf. is there a way to also bring it using dbghelp? currently 0 is the hardcoded `object_address` value returned from `resolve_frame()`

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, it is possible however it would come at a small performance cost. I'll try measuring the cost later to see if it matters.

**Comment by jeremy-rifkin** [comment]
It looks like calls to figure out the module for a raw address are cheap so I'll go ahead and set up the library to resolve this by default.
