### ISSUE TITLE
possible null dereference in file_deleter

### ISSUE THREAD

**Issue by eyalgolan1337** [jeremy-rifkin/cpptrace#106]
in `utils.hpp` there's this function:
```
inline void file_deleter(std::FILE* ptr) {
        fclose(ptr);
}
```
this function is used in `elf.hpp` in `elf_get_module_image_base()` inside a raii_wrap:
```static std::uintptr_t elf_get_module_image_base(const std::string& object_path) {
        auto file = raii_wrap(std::fopen(object_path.c_str(), "rb"), file_deleter);
        if(file == nullptr) {
            throw file_error("Unable to read object file " + object_path);
}
...
```
if `std::fopen` fails then the internal FILE* will be nullptr. using `fclose` on a nullptr is undefined behaviour (in my case - segmentation fault).

suggested fix:
```
inline void file_deleter(std::FILE* ptr) {
        if (ptr != nullptr) {
                fclose(ptr);
        }
}
```

This issue arose when the object file the library tried to open did not exist. the resulting object_trace came back empty, which is a shame since the other object files could probably still be opened, so a stack trace of all call addresses and partial object paths could have still been generated

**Comment by jeremy-rifkin** [comment]
Thanks, that’s also a good point. I think it may be taken care of as part of #102, which I hope to make progress on soon.
