### ISSUE TITLE
Add capability to choose libunwind as a setting in Conanfile

### ISSUE THREAD

**Issue by yfinkelstein** [jeremy-rifkin/cpptrace#110]
Currently it's impossible to to choose libunwind (not the gcc one but stand-alone one - the one that's signal safe) through Conan. 
I had to patch Conanfile to achieve it:
```
 def generate(self):
        tc = CMakeToolchain(self)
        if is_msvc(self):
            tc.variables["USE_MSVC_RUNTIME_LIBRARY_DLL"] = not is_msvc_static_runtime(self)
        if Version(self.version) >= Version("0.3.0"):
            tc.variables["CPPTRACE_USE_EXTERNAL_LIBDWARF"] = True
            tc.variables["CPPTRACE_UNWIND_WITH_LIBUNWIND"] = True
            tc.variables["CPPTRACE_CONAN"] = True
        else:
...
```
A lean way to do it is is probably to add it as an Option or maybe even a Setting.

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, it would definitely be good for the conanfile to be able to support this better.
