### ISSUE TITLE
compile Release: Cpptrace internal error: Libbacktrace error:no debug info in ELF executable, code: -1

### ISSUE THREAD

**Issue by Eternity1987** [jeremy-rifkin/cpptrace#114]
Cpptrace internal error: Libbacktrace error:no debug info in ELF executable, code: -1

**Comment by jeremy-rifkin** [comment]
Hi, this might be a simple issue of silently continuing on this error but a little additional information would be helpful. Did you compile with debug symbols?

I’ll also mention that the libbacktrace back-end is not recommended unless you have a good reason for using libbacktrace :)

**Comment by jeremy-rifkin** [comment]
I haven't been able to reproduce locally in debug however I have fixed this on the dev branch.

**Comment by Eternity1987** [comment]
I compiled the release version and not with optimization flags , and I want to obtain at least the address function name and the corresponding binary in the release version, without the need for specific file names and line numbers, but it throw exception and return null_frame, will show 0x00

**Comment by Eternity1987** [comment]
Ubuntu22.04 ok
![image](https://github.com/jeremy-rifkin/cpptrace/assets/15373993/3c24ce6c-7ae9-4e85-bd89-8e97aad5012b)
UUbuntu20.04 throw exception
![image](https://github.com/jeremy-rifkin/cpptrace/assets/15373993/80961ed0-fe22-46fd-99b1-9faa9eb87cfe)

**Comment by jeremy-rifkin** [comment]
Thanks. I think the patch should work for your use case, though it likely won't include function names without debug symbols.
