### ISSUE TITLE
older version of glibc does not produce stacktrace in signal tracing

### ISSUE THREAD

**Issue by WSUFan** [jeremy-rifkin/cpptrace#126]
It seems that in older versions of glibc (such as the one in Ubuntu 20), the following test will fail:
```c++
#include <dlfcn.h>
int main() {
    dl_find_object result;
    _dl_find_object(reinterpret_cast<void*>(main), &result);
}
```
As a result, cpptrace will not use `_dl_find_object` and will instead use `dlopen` (right?). This approach produces an empty stack trace (I guess the object path is not correct in this case?):

```bash
SIGSEGV occurred:
Stack trace (most recent call first):
<empty trace>
```
So, do we have any fallback functions to mimic the behavior of _dl_find_object?

Thanks!

**Comment by jeremy-rifkin** [comment]
Hi, correct, _dl_find_object is needed for getting information in a signal-safe way and I don’t know of any alternative. I should document that relatively recent glibc is needed.

**Comment by WSUFan** [comment]
Ok. Thanks for letting me know
