### ISSUE TITLE
Make it possible to use system gtest when it's available

### ISSUE THREAD

**Issue by xokdvium** [jeremy-rifkin/cpptrace#130]
Currently it's impossible to build unit tests without getting gtest via FetchContent.
It would be useful to either prefer system gtest by default or add a cmake option for
that behavior. This is necessary to run the build in sandboxed environments where FetchContent can't be used.

**Comment by jeremy-rifkin** [comment]
I'd be happy to support a way to use external gtest. Up until now no one has requested this. One thing to note though is that the current state of unit tests is pretty non-existent, I was trying to setup unit tests but it's very tricky.

**Comment by jeremy-rifkin** [comment]
Implemented on dev, will be part of the next release

**Comment by jeremy-rifkin** [comment]
Thanks for your patience, I've released v0.6.0
