### ISSUE TITLE
run signal-safe error

### ISSUE THREAD

**Issue by ccc120660** [jeremy-rifkin/cpptrace#137]
Hello,thanks to your library,but when i am running the signal-safe test, the result is:
![B85097A9C0037C723FB8D073846C4D51](https://github.com/jeremy-rifkin/cpptrace/assets/64881480/3c83a4bd-1491-4687-a8ea-aa9c369d750a)
I use the cpptrace 0.6.1,  glibc 2.28， and already installed libunwind 1.8.1
the Cmake command is:   cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCPPTRACE_STATIC_DEFINE=On -DCPPTRACE_UNWIND_WITH_LIBUNWIND=On
and the g++ command is:  
g++  /data/shared/test/coredump/signal_tracer.cpp -o /data/shared/test/coredump/signal_tracer  -Wall  -lcpptrace -ldwarf -lz -lzstd -ldl -lunwind
g++  /data/shared/test/coredump/signal_demo.cpp -o /data/shared/test/coredump/signal_demo  -Wall  -lcpptrace -ldwarf -lz -lzstd -ldl -lunwind

**Comment by ccc120660** [comment]
well，i saw the issue 126,  i will try to upgrade my glibc. = =

**Comment by jeremy-rifkin** [comment]
Thanks, I hope that works for you!
