### ISSUE TITLE
Is this a header-only library?

### ISSUE THREAD

**Issue by nyckmaia** [jeremy-rifkin/cpptrace#145]
Is this a header-only library?

Or do I need to include the whole folder in my project?

**Comment by jeremy-rifkin** [comment]
Hi,
This is not a header only library. There is information on how to use the library at https://github.com/jeremy-rifkin/cpptrace?tab=readme-ov-file#usage.

**Comment by 8ightfold** [comment]
Please read the docs/source before opening an issue. Thanks!

**Comment by jeremy-rifkin** [comment]
I'm going to go ahead and close this, if you have any further questions please don't hesitate to reach out
