### ISSUE TITLE
Link errr on macOS 14.6

### ISSUE THREAD

**Issue by hexabyte23** [jeremy-rifkin/cpptrace#151]
Got this message , any thoughts ?

ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[3](mach-o.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[4](module_base.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[5](object.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[7](safe_dl.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[8](cpptrace.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[10](demangle_with_cxxabi.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[13](snippet.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[14](debug_map_resolver.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[15](dwarf_resolver.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[16](symbols_core.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[21](symbols_with_libdwarf.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
ld: warning: object file (/Users/thierry/Dev/rcs/thirdparty/cpptrace-main/build/Replacement_for_Qt_for_macOS-Debug/libcpptrace.a[27](unwind_with_unwind.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (11.0)
Undefined symbols for architecture x86_64:
  "_dwarf_attr", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_string_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_unsigned_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      ...
  "_dwarf_child", referenced from:
      cpptrace::detail::libdwarf::die_object::get_child() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_convert_to_global_offset", referenced from:
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_dealloc", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::~dwarf_resolver() in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::~dwarf_resolver() in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_string_attribute(unsigned short) const::'lambda'(char*)::operator()(char*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&)::'lambda'(char*)::operator()(char*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&)::'lambda0'(char*)::operator()(char*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::resolve_filename(cpptrace::detail::libdwarf::die_object const&, unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_dealloc_attribute", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_string_attribute(unsigned short) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_unsigned_attribute(unsigned short) const::'lambda'(Dwarf_Attribute_s*)::operator()(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      ...
  "_dwarf_dealloc_die", referenced from:
      cpptrace::detail::libdwarf::die_object::~die_object() in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_dealloc_ranges", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Ranges_s*)::operator()(Dwarf_Ranges_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Ranges_s*)::operator()(Dwarf_Ranges_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_dealloc_rnglists_head", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Rnglists_Head_s*)::operator()(Dwarf_Rnglists_Head_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const::'lambda'(Dwarf_Rnglists_Head_s*)::operator()(Dwarf_Rnglists_Head_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_dieoffset", referenced from:
      cpptrace::detail::libdwarf::die_object::get_global_offset() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_errmsg", referenced from:
      cpptrace::detail::libdwarf::handle_dwarf_error(Dwarf_Debug_s*, Dwarf_Error_s*) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_errno", referenced from:
      cpptrace::detail::libdwarf::handle_dwarf_error(Dwarf_Debug_s*, Dwarf_Error_s*) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_find_die_given_sig8", referenced from:
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_finish", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::~dwarf_resolver() in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_formref", referenced from:
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_formsig8", referenced from:
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_formstring", referenced from:
      cpptrace::detail::libdwarf::die_object::get_string_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_formudata", referenced from:
      cpptrace::detail::libdwarf::die_object::get_ranges_offset(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_unsigned_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_arange", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::lookup_cu(unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_aranges", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::dwarf_resolver(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cpptrace::detail::optional<cpptrace::detail::libdwarf::skeleton_info, 0>) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_cu_die_offset", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::lookup_cu(unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_die_infotypes_flag", referenced from:
      cpptrace::detail::libdwarf::die_object::clone() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_ranges_b", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_rnglists_entry_fields_a", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_get_version_of_die", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::lookup_cu(unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::perform_dwarf_fission_resolution(cpptrace::detail::libdwarf::die_object const&, cpptrace::detail::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, 0> const&, cpptrace::object_frame const&, cpptrace::stacktrace_frame&, std::__1::vector<cpptrace::stacktrace_frame, std::__1::allocator<cpptrace::stacktrace_frame>>&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::lookup_cu(unsigned long long)::'lambda'(cpptrace::detail::libdwarf::die_object const&)::operator()(cpptrace::detail::libdwarf::die_object const&) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::lazy_generate_cu_cache()::'lambda'(cpptrace::detail::libdwarf::die_object const&)::operator()(cpptrace::detail::libdwarf::die_object const&) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_global_formref", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_ranges_offset(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf4_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(unsigned long long, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_hasattr", referenced from:
      cpptrace::detail::libdwarf::die_object::has_attr(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_highpc_b", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(int, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(int, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_init_path_a", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::dwarf_resolver(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cpptrace::detail::optional<cpptrace::detail::libdwarf::skeleton_info, 0>) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_lineaddr", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::get_line_table(cpptrace::detail::libdwarf::die_object const&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::get_line_table(cpptrace::detail::libdwarf::die_object const&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_lineendsequence", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_lineno", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_lineoff_b", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_linesrc", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_lowpc", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(int, cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(int, cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_next_cu_header_d", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::walk_compilation_units(std::__1::function<bool (cpptrace::detail::libdwarf::die_object const&)> const&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_offdie_b", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::lookup_cu(unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::clone() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_rnglists_get_rle_head", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_set_tied_dbg", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::dwarf_resolver(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cpptrace::detail::optional<cpptrace::detail::libdwarf::skeleton_info, 0>) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_siblingof_b", referenced from:
      cpptrace::detail::libdwarf::die_object::get_sibling() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_srcfiles", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::resolve_filename(cpptrace::detail::libdwarf::die_object const&, unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::resolve_filename(cpptrace::detail::libdwarf::die_object const&, unsigned long long) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_srclines_b", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::get_line_table(cpptrace::detail::libdwarf::die_object const&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_srclines_dealloc_b", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::~dwarf_resolver() in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_srclines_two_level_from_linecontext", referenced from:
      cpptrace::detail::libdwarf::dwarf_resolver::retrieve_line_info(cpptrace::detail::libdwarf::die_object const&, unsigned long long, cpptrace::stacktrace_frame&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::dwarf_resolver::get_line_table(cpptrace::detail::libdwarf::die_object const&) in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_tag", referenced from:
      cpptrace::detail::libdwarf::die_object::get_tag() const in libcpptrace.a[15](dwarf_resolver.cpp.o)
  "_dwarf_whatform", referenced from:
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::get_ranges_offset(Dwarf_Attribute_s*) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      void cpptrace::detail::libdwarf::die_object::dwarf5_ranges<cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)>(cpptrace::detail::libdwarf::die_object::pc_in_die(int, unsigned long long) const::'lambda'(unsigned long long, unsigned long long)) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
      cpptrace::detail::libdwarf::die_object::resolve_reference_attribute(unsigned short) const in libcpptrace.a[15](dwarf_resolver.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeremy-rifkin** [comment]
Hi, it looks like you might be linking against a static cpptrace? You'll need to link against libdwarf with `-ldwarf`, and possibly against additional libraries too: `-lz -lzstd -ldl`. Libdwarf and zstd are built alongside cpptrace by default, zlib and libdl should already be on your system.

**Comment by hexabyte23** [comment]
You are right, problem solved.
thank you

**Comment by hexabyte23** [comment]
You are right, problem solved.
thank you

**Comment by albar965** [comment]
You can disable the crashhandler by defining an environment variable `ATOOLS_NO_CRASHHANDLER=true`. This leaves the class [Crashhandler](https://github.com/albar965/atools/blob/release/4.0/src/util/crashhandler.h) as a hollow shell and disables all library and include requirements for cpptrace.

If needed you can compile cpptrace for LNM with the scripts in the build folder but I did not make any for macOS and Linux since these already have good error reporting. Might follow in the future.
