### ISSUE TITLE
Link error on WIN11

### ISSUE THREAD

**Issue by hexabyte23** [jeremy-rifkin/cpptrace#152]
Hello Jeremy,

Get somes problems again with win11 with MSVC2019, 

Linker complain with following params
-lws2_32 -luser32 -ldbghelp -L$$PWD/thirdparty/cpptrace-main/build/Desktop_Qt_6_7_2_MSVC2019_64bit-Debug -lcpptrace

link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /VERSION:2024.07 /MANIFEST:embed /OUT:..\..\bin\rcs.exe @C:\Users\thierry\AppData\Local\Temp\rcs.exe.49128.282.jom
main.obj : error LNK2019: symbole externe non r‚solu "__declspec(dllimport) public: void __cdecl cpptrace::stacktrace::print(void)const " (__imp_?print@stacktrace@cpptrace@@QEBAXXZ) r‚f‚renc‚ dans la fonction "void __cdecl onCrash(int)" (?onCrash@@YAXH@Z)
main.obj : error LNK2019: symbole externe non r‚solu "__declspec(dllimport) public: __cdecl cpptrace::stacktrace::~stacktrace(void)" (__imp_??1stacktrace@cpptrace@@QEAA@XZ) r‚f‚renc‚ dans la fonction "void __cdecl onCrash(int)" (?onCrash@@YAXH@Z)
main.obj : error LNK2019: symbole externe non r‚solu "__declspec(dllimport) struct cpptrace::stacktrace __cdecl cpptrace::generate_trace(unsigned __int64)" (__imp_?generate_trace@cpptrace@@YA?AUstacktrace@1@_K@Z) r‚f‚renc‚ dans la fonction "void __cdecl onCrash(int)" (?onCrash@@YAXH@Z)
..\..\bin\rcs.exe : fatal error LNK1120: 3 externes non r‚solus

**Comment by albar965** [comment]
Sorry, LNM does not compile with MSVC. You have to use the MINGW compiler that is shipped with the Qt installation. I use the Qt Creator IDE.

**Comment by jeremy-rifkin** [comment]
Hi, did you build cpptrace statically or dynamically? If you built it statically, make sure to set the `CPPTRACE_STATIC_DEFINE` preprocessor definition for your project.

**Comment by jeremy-rifkin** [comment]
I haven't heard back so I'm going to close this for now, please let me know if you have any more questions or run into any more issues!
