### ISSUE TITLE
Wishlist: Add some sort of DWARF back-end

### ISSUE THREAD

**Issue by jeremy-rifkin** [jeremy-rifkin/cpptrace#16]
It'd be great to have a custom DWARF back-end instead of relying on external dependencies such as libbacktrace or external programs such as addr2line. Such a back-end could make the library entirely self-contained on all platforms.

I don't know how to parse DWARF yet though, and the standard is massive.

**Comment by flagarde** [comment]
Maybe this library could be added more easily than libbacktrace https://github.com/davea42/libdwarf-code

**Comment by jeremy-rifkin** [comment]
Thank you so much @flagarde, that looks promising! The licensing looks compatible and it looks actively maintained. I can't immediately tell if it supports dwarf 5 but I can investigate.

**Comment by flagarde** [comment]
Don't think it's still dwarf5 ready

**Comment by jeremy-rifkin** [comment]
Baseline completed in #24
