### ISSUE TITLE
from_current.cpp compilation failed for iOS

### ISSUE THREAD

**Issue by tqjxlm** [jeremy-rifkin/cpptrace#163]
The new from_current.cpp file fails to compile for iOS. The error says "Use of undeclared identifier 'mach_vm_region'". I believe this function is MacOS-only.
I have been using this library with iOS for some time. I can confirm it works well before this update.

**Comment by jeremy-rifkin** [comment]
Thanks for opening this. I haven't tested on an iOS toolchain, I'll look into what should be done there and also adding that to CI so this doesn't break in the future.

**Comment by jeremy-rifkin** [comment]
Should be fixed on dev
