### ISSUE TITLE
Link dependencies statically?

### ISSUE THREAD

**Issue by SeeRich** [jeremy-rifkin/cpptrace#187]
Is it possible to link some of the dependencies statically so that my application doesn't depend on them at runtime. Specifically libunwind but also libz and libzstd?

**Comment by jeremy-rifkin** [comment]
Hi, it's definitely possible, at least in theory. You'd need static build of all those libraries and if you point cmake to those (e.g. with various cmake path environment variables) it should do the right thing. Unfortunately there's not an easy ergonomic solution for this.

**Comment by Ttibsi** [comment]
This is perfect timing, this is the same thing I'm trying to do right now. I see the comment at the top of `cmake/FindZstd.cmake` mentions a static target. Is there a way to force  cpptrace to find a static version when I'm using fetchcontent to add cpptrace to my own project?

**Comment by jeremy-rifkin** [comment]
By default everything is built statically:
```
› cmake .. -GNinja -DCPPTRACE_BUILD_TESTING=On
› ninja
› ls | grep libcpptrace
libcpptrace.a
› ldd demo
        linux-vdso.so.1 (0x00007ffd42ccb000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4515aa5000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4515827000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f45157f9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45155e7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f45154fe000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4515ba1000)
```

The one exception being zlib as the build setup finds the system's shared zlib. This is handled on the libdwarf side of things, it seems. Libdwarf's cmake does `find_package(ZLIB)` so if for some reason you want to link against a static zlib you can build zlib statically and point cmake to it with `ZLIB_ROOT`. 

I hope this helps! I'm going to mark solved for now, please let me know if you run into any issues.
