### ISSUE TITLE
`cpptrace` does not define a CMake "export set"

### ISSUE THREAD

**Issue by Jacobfaib** [jeremy-rifkin/cpptrace#189]
Adding `cpptrace` as a thirdparty lib to a target which expects to generate export lists ends with the following error:
```
CMake Error in CMakeLists.txt:
  export called with target "foo" which requires target "cpptrace-lib"
  that is not in any export set.
```
To reproduce
```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.26.4)

project(foo VERSION 1.0)

include(FetchContent)
FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  GIT_TAG        v0.7.2 # <HASH or TAG>
)
FetchContent_MakeAvailable(cpptrace)

add_library(foo foo.cpp)

target_link_libraries(foo PRIVATE cpptrace::cpptrace)

install(TARGETS foo
        EXPORT foo-exports
        DESTINATION lib)

export(EXPORT foo-exports
       FILE "${CMAKE_CURRENT_BINARY_DIR}/foo-targets.cmake")
```
```sh
$ cd cpptrace_bug
$ touch foo.cpp
# copy in CMakeLists.txt above
$ cmake -S . -B bug
```
------
The fix appears to be 
```diff
diff --git a/cmake/InstallRules.cmake b/cmake/InstallRules.cmake
index 529e51a..a36a9bd 100644
--- a/cmake/InstallRules.cmake
+++ b/cmake/InstallRules.cmake
@@ -62,6 +62,12 @@ install(
   COMPONENT ${package_name}-development
 )

+export(
+  TARGETS ${target_name}
+  NAMESPACE cpptrace::
+  FILE "${PROJECT_BINARY_DIR}/${package_name}-targets.cmake"
+)
+
 # Findzstd.cmake
 # vcpkg doesn't like anything being put in share/, which is where this goes apparently on their setup
 if(NOT CPPTRACE_VCPKG)
```
but I'm no CMake guru, so perhaps there are other changes required to make this more robust...

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, I think the patch looks reasonable to me. I can test and merge later today.

**Comment by jeremy-rifkin** [comment]
Locally I'm seeing
```
CMake Error in CMakeLists.txt:
  export called with target "cpptrace-lib" which requires target "dwarf" that
  is not in any export set.
```

I'm going to have to investigate, it may just be a matter of adding the same thing upstream

**Comment by Jacobfaib** [comment]
Yeah I think it's the same problem. It's a shame that the cmake error message is so uninformative. The only way I knew about the solution here is because I happened to run into this error _after_ removing an `export()` call in a previous project...

**Comment by jeremy-rifkin** [comment]
I've PR'd a patch upstream and it looks like in the meantime I can provide the export() for libdwarf in cpptrace's cmake. This is a bit of a hack but it seems to work and hopefully it'll unblock any issues for now.

I've added two options `CPPTRACE_PROVIDE_EXPORT_SET` and `CPPTRACE_PROVIDE_EXPORT_SET_FOR_LIBDWARF` in case a user ever needs to turn off the hack or the cpptrace export(). I'll remove the hack once merged upstream.

**Comment by jeremy-rifkin** [comment]
0.7.3 is released
