### ISSUE TITLE
Include path missing

### ISSUE THREAD

**Issue by mvitorovic** [jeremy-rifkin/cpptrace#28]
I couldn't make the "Quick Setup with CMake FetchContent" working without adding the following line:

`include_directories(_deps/cpptrace-src/include)`

P.S. Making a fork for one line in the README seemed like too much overhead.

**Comment by jeremy-rifkin** [comment]
Hello, thanks for the report! I'll look into this. What did you specify for `GIT_TAG`? I'd recommend `v0.1.1` as main is somewhat unstable at the moment (working on overhauling some internals).

**Comment by mvitorovic** [comment]
Thanks for the quick reply. I used the latest commit SHA. Did not try with the tag. I'll do that now.

**Comment by jeremy-rifkin** [comment]
Hi @mvitorovic, things have now stabalized with the reworking I've done and it looks like cmake + fetchcontent is working.

(I tested with:

```cmake
cmake_minimum_required(VERSION 3.8)

project(demo_project VERSION 0.0.1 LANGUAGES CXX)

add_executable(main main.cpp)

include(FetchContent)
FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  GIT_TAG        main # <HASH or TAG>
)
FetchContent_MakeAvailable(cpptrace)
target_link_libraries(main cpptrace)

target_compile_features(main PRIVATE cxx_std_11)
```
)
