### ISSUE TITLE
Problem with libdwarf

### ISSUE THREAD

**Issue by mvitorovic** [jeremy-rifkin/cpptrace#29]
After building the project with cpptrace and running it I get the following error:

`libdwarf error reading xx: 468 DW_DLE_RNGLISTS_ERROR(468) Corrupt dwarf. Bad .debug_rnglists data.` 

The project is compiled with clang++
`$ clang++ --version`
`Debian clang version 14.0.6`
`Target: x86_64-pc-linux-gnu`
`Thread model: posix`
`InstalledDir: /usr/bin`

**Comment by jeremy-rifkin** [comment]
Thanks for opening this issue. I noticed it recently when developing locally, it is related to performing lookups in dwarf 5 with `dwarf5_ranges`. 

For now either use v0.1.1 of the library until main is stabilized or use `-gdwarf-4` when compiling with clang.

**Comment by jeremy-rifkin** [comment]
I hope to have this issue resolved soon though

**Comment by mvitorovic** [comment]
I can confirm it work well with tag v0.1.1

Thanks for your help.

**Comment by jeremy-rifkin** [comment]
Excellent, thanks for confirming!

**Comment by jeremy-rifkin** [comment]
This is now resolved with f5fd6942e284ad7ce21528d59666ec283802994c (I based the dwarf5 ranges code in another repository, now patched there as well with https://github.com/davea42/libdwarf-addr2line/pull/1), and a tangentially related bug is solved with 9cb840c72351fb29a10a58a15bab7cf89f5777ac.
