### ISSUE TITLE
dsymutil and CMake

### ISSUE THREAD

**Issue by flagarde** [jeremy-rifkin/cpptrace#31]
First thx a lot for this library !

I have seen in the README that in Macos we need to generate file by ourself. It seems using XCOde CMake has some variables to ask xcode to generate them and for other generator there is a discussion on [dsymutil](https://gitlab.kitware.com/cmake/cmake/-/issues/20256). Not sure if it's working but if so maybe it would simplify the process

**Comment by jeremy-rifkin** [comment]
Hey @flagarde, thanks so much! I'll look into these. I'm hoping to get away from the dsymutil requirement soon but it would be a cleaner solution for now (and anyone in the future needing a symbol archive).

**Comment by jeremy-rifkin** [comment]
I've added a note to the readme about this, thank you again
