### ISSUE TITLE
libdwarf 5 still making problems

### ISSUE THREAD

**Issue by mvitorovic** [jeremy-rifkin/cpptrace#32]
Hi Jeremy,

after getting an email about closing the issue #29 I wanted to test the latest build.

FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  GIT_TAG        29b3140ddd15d7ef2d71fdc7180e247c82bca7d5 # <HASH or TAG>
)
FetchContent_MakeAvailable(cpptrace)

After running cmake again I get a new error:
`Deuteros: /home/miha/workspace/deuteros/_deps/cpptrace-src/src/symbols/symbols_with_libdwarf.cpp:131: int dwarf5_ranges(Dwarf_Die, Dwarf_Addr *, Dwarf_Addr *): Assertion 'false' failed.
Aborted
`

Sorry :)

**Comment by jeremy-rifkin** [comment]
Thanks! I’ll take a look.

**Comment by jeremy-rifkin** [comment]
Ah, silly mistake on my part. Should be fixed now.

**Comment by jeremy-rifkin** [comment]
(accidentally messed up the commits and had to force push / repush)
