### ISSUE TITLE
Feature request for supporting gnu-debuglink'd symbols

### ISSUE THREAD

**Issue by cstaylor** [jeremy-rifkin/cpptrace#39]
Would it be possible to support stack traces for binaries that have their dwarf symbols moved into a separate file like:
```
g++ -g -O0 file1.cc file2.cc ... -lcpptrace -o runme
objcopy --only-keep-debug runme runme.dbg
strip --strip-debug --strip-unneeded runme
objcopy --add-gnu-debuglink=runme.dbg runme
```
With `v0.2.0-alpha` filename and line number information is missing from stack traces when I use the above steps, even though gdb can load the symbols without any problems.

Thank you!

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, it should definitely be possible I just have to learn how to do it. I definitely want to support this use case.

**Comment by cstaylor** [comment]
If there's anything I can do to help, please let me know.

**Comment by jeremy-rifkin** [comment]
Cpptrace now supports debuglink as of 99230cb8fe4e5481b20a713e60d1b9a93f5f8cef

**Comment by jeremy-rifkin** [comment]
Thanks for your patience and interest in the library!
