### ISSUE TITLE
Interface change

### ISSUE THREAD

**Issue by mvitorovic** [jeremy-rifkin/cpptrace#44]
Hi Jeremy,

it's me again :)
I'm testing v0.2.0-beta
README needs updating, since `struct stacktrace` no longer contains a member `empty()`.

Otherwise it's working fine! Thanks!

**Comment by jeremy-rifkin** [comment]
Hey! Thank you so much, I am immensely grateful for your interest in the library and for catching my mistakes :)

**Comment by jeremy-rifkin** [comment]
And also very glad to hear it’s working otherwise

**Comment by jeremy-rifkin** [comment]
`empty()` was added after the v0.2.0-beta tag I think. The library's interface has been changing quickly as I've been trying to expand functionality. I'll try to do another prerelease soon.

**Comment by jeremy-rifkin** [comment]
I've bumped the version in the readme and made another prerelease so should be good now
