### ISSUE TITLE
Consider conditionally disabling exception classes if `-fno-exceptions` is set

### ISSUE THREAD

**Issue by Sirraide** [jeremy-rifkin/cpptrace#55]
Currently, the library fails to compile w/ `-fno-exceptions` due to the use of `try` statements in `cpptrace.hpp`. At least for GCC and Clang, an easy solution would be to conditionally disable the exception classes by wrapping them in `#ifdef __EXCEPTIONS` ... `#endif`. The `__EXCEPTIONS` macro is defined, iff `-fno-exceptions` is not set. This seems to be all that needs to be done to get it to compile again.

I’m not sure how MSVC handles any of this, so another option would also be to simply make this configurable at build time. The library seems to work just fine even if those classes are removed or conditionally disabled, so for people (like me) who only want to use it for the backtraces and don’t care too much about exceptions, this would be a nice addition.

**Comment by jeremy-rifkin** [comment]
Hi, thanks for opening this issue!

**Comment by jeremy-rifkin** [comment]
This has been fixed in dev as there are no longer any `try`'s in cpptrace.hpp

**Comment by Ghost-LZW** [comment]
Seems like the library fails to compile w/ `-fno-exceptions` again, with this change https://github.com/jeremy-rifkin/cpptrace/commit/acaa4f42e619863f044b06efd62673727029c573#diff-b511347622ba58cb6abfdcabcbbe31698a6598b5af09201398bf91b8352959b7R62-R66

**Comment by jeremy-rifkin** [comment]
Hi, I'm able to compile programs using cpptrace with `-fno-exceptions`. The library itself cannot be compiled with `-fno-exceptions` because of internal error handling.

**Comment by Ghost-LZW** [comment]
Thanks, it is indeed able to build this library without the -no-exceptions flag and then link it with a no-exceptions library. However, I found that without exception support, the stack will be empty. I think I need to open another issue with an simple example.
