### ISSUE TITLE
Consider using FetchContent to populate libdwarf

### ISSUE THREAD

**Issue by flagarde** [jeremy-rifkin/cpptrace#56]
Hi, thx for this library.

It could be nice to have the possibility to fetch the libdwarf to avoid to update libdwarf each time there is a new version. It could even allow to have an other source for libwarf.

**Comment by jeremy-rifkin** [comment]
Hi @flagarde,
Overall I thought it was simpler to just bundle libdwarf but I'm open to adding a FetchContent option. Part of the benefit of bundling was I could use a custom cmake, unfortunately the upstream cmake is a bit of a mess. I'd need to look into it some more.

**Comment by flagarde** [comment]
@jeremy-rifkin hi, In fact it's indeed why FetchContent could be interesting because you can choose which tag and git repo to use. The only draw backs I see is :

* You need internet connection to configure it at first. But you could imagine to ship libdwarf inside the released version archive to avoid that.

* You need a more modern cmake version 3.14 if I rememnber well, still quite old anyway. 

The main problem with the actual libdwarf is that it finds zlib and the other dependency by hardcoded way and as such you can't choose where it tries to find them. That's problematic as it could be maybe more interesting for this library beeing backtrace library to avoid .so and to be statically linked with all this dependencies. The other problem if that the Config file given by libdwarf doesn't checks its dependencies. If it's has used the shared library dependencies That's bad. Theoretically these libraries could have been removed or in other directory than when cpptrace has been compiled. For now there is no way to have good error in this case in find_package and you need to hack your Config file to do this yourself but this should better done in libdward. 

My goal would be to use a specific libdwarf package (You could have one sitted on your account) to fix that and even allow libdwarf to fetch and compile it's dependencies (zlib,and the other one) in static, shared libraries and link to the static ones.

**Comment by jeremy-rifkin** [comment]
I'm going to try to unbundle libdwarf in #58. Pending https://github.com/davea42/libdwarf-code/pull/193 for properly using upstream libdwarf.

**Comment by jeremy-rifkin** [comment]
I think this should be good to go in the next release

**Comment by flagarde** [comment]
@jeremy-rifkin  [#197](https://github.com/davea42/libdwarf-code/pull/197) [#196](https://github.com/davea42/libdwarf-code/pull/196) has been merged so now libdwarf use the `find_package` function as such it is now easier to create a dummy repo Fetching zlib zstd and libdwarf to compile all in static

**Comment by jeremy-rifkin** [comment]
Oh cool, thanks @flagarde!
