### ISSUE TITLE
How to print the trace when segmentation fault happened

### ISSUE THREAD

**Issue by BigFaceBoy** [jeremy-rifkin/cpptrace#73]

**Comment by jeremy-rifkin** [comment]
Hi @BigFaceBoy, signal-safe stack tracing is tricky to do. You may be able to simply call `cpptrace::generate_trace().print()` from a signal handler and get away with it, but it's risky (segfaulting again or deadlocking are the primary concerns). I have written up instructions for how to do this safely at https://github.com/jeremy-rifkin/cpptrace#signal-safe-tracing and https://github.com/jeremy-rifkin/cpptrace/blob/main/signal-safe-tracing.md. Hope these help, I'm happy to help with any additional questions!

**Comment by BigFaceBoy** [comment]
@jeremy-rifkin Hello. In `signal_demo.cpp` , register  the handler to sigaction. I wonder how  to ensure that the handler will be called.
In my program, I register a handler to sigaction for printing the call stack when segmentation fault happened. But sometimes it will not print the call stack, the handler may not be called.

**Comment by jeremy-rifkin** [comment]
I don't know of any way right off hand that a sigaction handler could not be called when that signal fires. If you're able to reproduce, are you able to observe anything in gdb? Does something go wrong in your handler? Does your program SIGSEGV or is it another signal?

**Comment by BigFaceBoy** [comment]
@jeremy-rifkin Thanks, I will debug with gdb to find out what cause this

**Comment by BigFaceBoy** [comment]
@jeremy-rifkin

**Comment by jeremy-rifkin** [comment]
Hi @BigFaceBoy, unfortunately both using `std::cout` and `cpptrace::generate_trace().print();` are not async-signal-safe so it's not guaranteed to work. It's very possible you could be hitting a deadlock or some other critical error that results in an abort or trap. The https://github.com/jeremy-rifkin/cpptrace/blob/main/signal-safe-tracing.md doc provides an example for how to do this safely, it is unfortunately a lot of work but it's pretty much the only way to truly do this safely.

**Comment by BigFaceBoy** [comment]
@jeremy-rifkin Hello， I build the demo  signal_demo.cpp and signal_tracer.cpp， the run signal_demo. It prints:
SIGSEGV ocurred:
Stack trace (most recent call first):
<empty trace>

**Comment by jeremy-rifkin** [comment]
Have you configured cpptrace to use libunwind? Unfortunately that's the only way to do signal-safe unwinding. If you haven't, clear your build directory / cmake cache and configure with `-DCPPTRACE_UNWIND_WITH_LIBUNWIND=On`. This does require you to have libunwind installed.

**Comment by BigFaceBoy** [comment]
@jeremy-rifkin I compiled with -DCPPTRACE_UNWIND_WITH_LIBUNWIND=On. But I still get empty trace:
SIGSEGV ocurred:
Oops, size mismatch 4120 4120
Stack trace (most recent call first):
empty trace

![image](https://github.com/jeremy-rifkin/cpptrace/assets/12423597/6be10455-664b-4034-83b9-9e1a3ddc15dd)

![image](https://github.com/jeremy-rifkin/cpptrace/assets/12423597/ef0dd91e-edfd-43da-bac1-02e58707a71c)

**Comment by jeremy-rifkin** [comment]
`size mismatch 4120 4120` is odd to me, fread should be reading exactly one item and returning `1` if successful. What system are you on? Does `-DCMAKE_BUILD_TYPE=Debug` change anything?

**Comment by jeremy-rifkin** [comment]
Thanks @BigFaceBoy, I'll look into this more

**Comment by jeremy-rifkin** [comment]
Sorry this hasn't been as seamless as a process as I'd have liked. Unfortunately to do these traces safely a lot of logistics are required. The `Unable to read file Unable to read object file` error seems to indicate the library is trying to open a blank path, so it'd probably make sense to skip the `frame.resolve()` any time `frame.object_path` is empty.

I can update the signal demo to do this, or update the internal handling to better deal with this.

I'm going to close this for now. Thank you for your patience and please let me know if there's anything else I can help with or if you run into any additional issues.
