### ISSUE TITLE
libdwarf undefined reference to 'uncompress'

### ISSUE THREAD

**Issue by vereena0x13** [jeremy-rifkin/cpptrace#74]
I have cloned the repo, checked out v0.3.1, and built it as such:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DCPPTRACE_STATIC=On
make -j
make install
```

When I try to build my program with cpptrace linked in, I am getting this error:
```
/usr/bin/ld: vendor/cpptrace/install/lib/libdwarf.a(dwarf_init_finish.c.o): in function `_dwarf_load_section':
dwarf_init_finish.c:(.text+0x3bb): undefined reference to `uncompress'
```

I have also tried setting `CPPTRACE_USE_EXTERNAL_LIBDWARF=On` but the result is the same.

**Comment by jeremy-rifkin** [comment]
Thanks for opening this issue, does your system have zlib or zstd installed?

**Comment by vereena0x13** [comment]
I have the following packages installed (arch linux):
```
lib32-zlib 1.3-1
zlib 1:1.3-2
lib32-zstd 1.5.5-1
zstd 1.5.5-1
```

And I see the following messages printed during config:
```
-- Performing Test HAVE_ZLIB
-- Performing Test HAVE_ZLIB - Success
-- Performing Test HAVE_ZLIB_H
-- Performing Test HAVE_ZLIB_H - Success
-- Performing Test HAVE_ZSTD
-- Performing Test HAVE_ZSTD - Success
-- Performing Test HAVE_ZSTD_H
-- Performing Test HAVE_ZSTD_H - Success
```

**Comment by jeremy-rifkin** [comment]
Thanks for checking, I'm wondering if something is up with the handling of transitive dependencies then. Does your program compile if you do `target_link_libraries(yourprogram PRIVATE z zstd)`?

**Comment by vereena0x13** [comment]
I'm not building my program with CMake. All I did to link to cpptrace was the add the following to my makefile:
```
debug: CXXFLAGS+=-Ivendor/cpptrace/install/include
debug: LDFLAGS+=-Lvendor/cpptrace/install/lib -lcpptrace -ldwarf
```

**Comment by jeremy-rifkin** [comment]
Oh I see! My bad for assuming you were building with cmake. It should work with `-lz -lzstd` then (I think both are required), I will update the library's documentation to indicate that this is needed.

**Comment by vereena0x13** [comment]
Adding `-lz` fixed it! It doesn't seem to require `-lzstd` though.
Thank you so much!

**Comment by jeremy-rifkin** [comment]
Awesome thanks for checking -lzstd!
